---
# We'll use the admin account to access OpenSwitch switches.
ansible_user: root

# Those will be secured by the ansible vault in the real environment.
ops_username: netop
ops_password: netop

# ops_command provider for CLI transport.
ops_cli_provider:
  transport: cli
  username: "{{ ops_username }}"
  password: "{{ ops_password }}"
  host: "{{ ansible_host }}"
  port: "{{ ansible_port }}"

# ops_command provider for REST transport.
ops_rest_port: 443
ops_rest_provider:
  transport: rest
  username: "{{ ops_username }}"
  password: "{{ ops_password }}"
  host: "{{ ansible_host }}"
  port: "{{ ops_rest_port }}"
  use_ssl: true
  validate_certs: no

# Just use the inventory name as the host name.
ops_system_hostname: "{{ inventory_hostname }}"

# Every switch shares ops_bridge configuration for now.
#ops_bridges:
#  - name: bridge_normal
#    ports: [1, 2, 3, 4, 5, 6, 7, 8]
#    vlans:
#      - name: VLAN10
#        id: 10

# Only eight ports will be used in this environment.
ops_interfaces:
  - name: 1
  - name: 2
  - name: 3
  - name: 4
  - name: 5
  - name: 6
  - name: 7
  - name: 8
  - name: 9
