---
- name: BGP configuration on fabric switches
  hosts: fabrics
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - { role: bgp, tags: [ config ] }

- name: BGP configuration on spine switches
  hosts: spines
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - { role: bgp, tags: [ config ] }

- name: BGP configuration on leaf switches
  hosts: leaves
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - { role: bgp, tags: [ config ] }

- name: check the switch configuration
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: yes
  tasks:
    - include: tasks/cli/check_running_config.yaml
      tags: [ check ]

- name: wait for BGP peering up
  hosts: switches
  gather_facts: no
  tasks:
    - pause: seconds=90

- name: check the BGP peering
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: no
  tasks:
    - name: show ip bgp neighbors
      tags: [ check ]
      connection: local
      ops_command:
        commands:
          - show ip bgp neighbors
        provider: "{{ ops_cli_provider }}"
        waitfor:
          - "result[0] contains 'state: Established'"
        interval: 3
        retries: 3
      register: result

    - name: print out the result
      tags: [ check ]
      debug: var=result

- name: check the BGP RIB
  hosts: switches
  gather_facts: yes
  vars:
    ops_debug: no
  tasks:
    - name: show ip bgp
      connection: local
      tags: [ check ]
      ops_command:
        commands:
          - show ip bgp
        provider: "{{ ops_cli_provider }}"
        waitfor:
          - "result[0] contains '172.16.0.0/24'"
          - "result[0] contains '172.16.1.0/24'"
          - "result[0] contains '172.16.2.0/24'"
          - "result[0] contains '172.16.11.0/24'"
          - "result[0] contains '172.16.12.0/24'"
          - "result[0] contains '172.16.21.0/24'"
          - "result[0] contains '172.16.22.0/24'"
          - "result[0] contains '172.16.30.0/24'"
          - "result[0] contains '172.16.31.0/24'"
          - "result[0] contains '172.16.40.0/24'"
          - "result[0] contains '172.16.41.0/24'"
          - "result[0] contains '172.16.50.0/24'"
          - "result[0] contains '172.16.51.0/24'"
          - "result[0] contains '172.16.60.0/24'"
          - "result[0] contains '172.16.61.0/24'"
        interval: 3
        retries: 3
      register: result

    - name: print out the result
      tags: [ check ]
      debug: var=result
