---
- name: make all traffic to 172.16.0.0/16 through eth1
  hosts: servers
  gather_facts: no
  tasks:
    - name: add 172.16.0.0/16 through eth1
      tags: [ server, config ]
      become: yes
      command: ip route add 172.16.0.0/16 dev eth1
      register: result
      failed_when: result.rc != 0 and not result.stderr | search('File exists')
      changed_when: result.rc == 0
