---
- name: check running-config CLI output
  ops_command:
    provider: "{{ ops_cli_provider }}"
    commands:
      - show running-config
    waitfor:
      - "result[0] contains 'hostname {{ ops_system_hostname }}'"
    interval: 5
    retries: 3
  register: result
  connection: local

- name: print the CLI output
  debug: var=result
  when: ops_debug
