---
- name: check the version through /system REST output
  connection: local
  ops_facts:
    provider: "{{ ops_rest_provider }}"
    endpoints:
      - /system
  register: result
  failed_when: "'{{ expected }}' != endpoints[0].status.software_info.os_name"

- name: print the REST output
  debug: var=result
  when: ops_debug
