# Based on the deprecated ansible docker image:
#
# https://hub.docker.com/r/ansible/ubuntu14.04-ansible/
#
# especially, this Dockerfile:
#
# https://github.com/ansible/ansible-docker-base/blob/master/devel-ubuntu14.04/Dockerfile
#
FROM ubuntu:14.04

MAINTAINER Kei Nohguchi <kei@nohguchi.com>

# Copy the ssh private key
RUN mkdir /root/.ssh
ADD id_rsa /root/.ssh/id_rsa
RUN chmod 0700 /root/.ssh
RUN chmod 0400 /root/.ssh/id_rsa

# Prepare the ansible environment
RUN mkdir /etc/ansible

# Required package(s)
RUN apt-get -y update && \
    apt-get install -y openssh-client git \
                       python-keyczar python-setuptools \
                       python-pkg-resources

# http://docs.ansible.com/ansible/intro_installation.html#running-from-source
RUN easy_install pip
RUN pip install paramiko PyYAML Jinja2 httplib2 six

# Get the latest ansible
RUN mkdir /opt/ansible
# Waiting ansible PR #1513
# https://github.com/ansible/ansible/pull/1513
#RUN git clone https://github.com/ansible/ansible.git \
#        --recursive /opt/ansible/ansible
RUN git clone https://github.com/keinohguchi/ansible.git \
        --branch net_template_fix /opt/ansible/ansible
RUN git clone https://github.com/ansible/ansible-modules-core.git \
	/opt/ansible/ansible/lib/ansible/modules/core
WORKDIR /opt/ansible/ansible
ENV PATH /opt/ansible/ansible/bin:/bin:/usr/bin:/sbin:/usr/sbin
ENV PYTHONPATH /opt/ansible/ansible/lib
ENV ANSIBLE_LIBRARY /opt/ansible/ansible/library
