version: '2'
services:
  build:
    build: .
    image: openswitch/local_build
    command: /bin/true
  build:
    build: ./server
    image: server/local_build
    command: /bin/true
  fab1:
    image: openswitch/local_build
    container_name: "fab1"
    privileged: true
    ports:
      - "10022:22"
      - "10443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  spine1:
    image: openswitch/local_build
    container_name: "spine1"
    privileged: true
    ports:
      - "11022:22"
      - "11443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  spine2:
    image: openswitch/local_build
    container_name: "spine2"
    privileged: true
    ports:
      - "12022:22"
      - "12443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  server1:
    image: server/local_build
    container_name: "server1"
    ports:
      - "21022:22"
    networks:
      - default
    command: /usr/sbin/sshd -D
