version: '2'
services:
  build:
    build: .
    image: openswitch/local_build
    command: /bin/true
  fab1:
    image: openswitch/local_build
    container_name: "fab1"
    privileged: true
    ports:
      - "10022:22"
      - "10433:433"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  spine1:
    image: openswitch/local_build
    container_name: "spine1"
    privileged: true
    ports:
      - "11022:22"
      - "11433:433"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  spine2:
    image: openswitch/local_build
    container_name: "spine2"
    privileged: true
    ports:
      - "12022:22"
      - "12433:433"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  leaf1:
    image: openswitch/local_build
    container_name: "leaf1"
    privileged: true
    ports:
      - "13022:22"
      - "13433:433"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  leaf2:
    image: openswitch/local_build
    container_name: "leaf2"
    privileged: true
    ports:
      - "14022:22"
      - "14433:433"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  leaf3:
    image: openswitch/local_build
    container_name: "leaf3"
    privileged: true
    ports:
      - "15022:22"
      - "15433:433"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  leaf4:
    image: openswitch/local_build
    container_name: "leaf4"
    privileged: true
    ports:
      - "16022:22"
      - "16433:433"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
