---
- name: check fabric switch health
  hosts: fabrics
  gather_facts: no
  vars:
    ansible_user: admin
  tasks:
    - ping:
              
- name: check spine switch health
  hosts: spines
  gather_facts: no
  vars:
    ansible_user: admin
  tasks:
    - ping:
              
- name: check leaf switch health
  hosts: leaves
  gather_facts: no
  vars:
    ansible_user: admin
  tasks:
    - ping:

- name: check server health
  hosts: servers
  gather_facts: no
  vars:
    ansible_user: admin
  tasks:
    - ping:
