---
- name: wipe switch config
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: root
    ops_debug: yes
  roles:
    - role: switch
      ops_vrfs:
        - name: vrf_default
          ports: []
      ops_bridges:
        - name: bridge_normal
          vlans: []
          ports: []
      ops_interfaces:
        - name: 1
        - name: 2
        - name: 3
        - name: 4
        - name: 5
        - name: 6
        - name: 7
        - name: 8
        - name: 9
        - name: 10
      ops_ports:
        - name: 1
        - name: 2
        - name: 3
        - name: 4
        - name: 5
        - name: 6
        - name: 7
        - name: 8
        - name: 9
        - name: 10
