---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    bgp_routers:
      - as_number: 64700
        router_id: 10.10.11.1
        networks: [10.10.11.0/24, 10.10.12.0/24, 10.10.13.0/24, 10.10.14.0/24, 10.10.15.0/24, 10.10.16.0/24, 10.10.17.0/24, 10.10.18.0/24, 10.40.11.0/24]
        neighbors:
          - address: 10.10.11.2
            remote_as: 64850
          - address: 10.10.12.2
            remote_as: 64850
          - address: 10.10.13.2
            remote_as: 64850
          - address: 10.10.14.2
            remote_as: 64850
          - address: 10.10.15.2
            remote_as: 64851
          - address: 10.10.16.2
            remote_as: 64851
          - address: 10.10.17.2
            remote_as: 64851
          - address: 10.10.18.2
            remote_as: 64851
          - address: 10.40.11.2
            remote_as: 64701
ops_ports:
  - name: 1
    ipv4_address: 10.10.11.1/24
  - name: 2
    ipv4_address: 10.10.12.1/24
  - name: 3
    ipv4_address: 10.10.13.1/24
  - name: 4
    ipv4_address: 10.10.14.1/24
  - name: 5
    ipv4_address: 10.10.15.1/24
  - name: 6
    ipv4_address: 10.10.16.1/24
  - name: 7
    ipv4_address: 10.10.17.1/24
  - name: 8
    ipv4_address: 10.10.18.1/24
  - name: 9
    ipv4_address: 10.40.11.1/24
