---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    bgp_routers:
      - as_number: 64700
        router_id: 10.10.31.1
        networks: [10.10.31.0/24, 10.10.32.0/24, 10.10.33.0/24, 10.10.34.0/24, 10.10.35.0/24, 10.10.36.0/24, 10.10.37.0/24, 10.10.38.0/24, 10.40.13.0/24]
        neighbors:
          - address: 10.10.31.2
            remote_as: 64850
          - address: 10.10.32.2
            remote_as: 64850
          - address: 10.10.33.2
            remote_as: 64850
          - address: 10.10.34.2
            remote_as: 64850
          - address: 10.10.35.2
            remote_as: 64851
          - address: 10.10.36.2
            remote_as: 64851
          - address: 10.10.37.2
            remote_as: 64851
          - address: 10.10.38.2
            remote_as: 64851
          - address: 10.40.13.2
            remote_as: 64701
ops_ports:
  - name: 1
    ipv4_address: 10.10.31.1/24
  - name: 2
    ipv4_address: 10.10.32.1/24
  - name: 3
    ipv4_address: 10.10.33.1/24
  - name: 4
    ipv4_address: 10.10.34.1/24
  - name: 5
    ipv4_address: 10.10.35.1/24
  - name: 6
    ipv4_address: 10.10.36.1/24
  - name: 7
    ipv4_address: 10.10.37.1/24
  - name: 8
    ipv4_address: 10.10.38.1/24
  - name: 9
    ipv4_address: 10.40.13.1/24
