---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    bgp_routers:
      - as_number: 64700
        router_id: 10.10.41.1
        networks: [10.10.41.0/24, 10.10.42.0/24, 10.10.43.0/24, 10.10.44.0/24, 10.10.45.0/24, 10.10.46.0/24, 10.10.47.0/24, 10.10.48.0/24, 10.40.14.0/24]
        neighbors:
          - address: 10.10.41.2
            remote_as: 64850
          - address: 10.10.42.2
            remote_as: 64850
          - address: 10.10.43.2
            remote_as: 64850
          - address: 10.10.44.2
            remote_as: 64850
          - address: 10.10.45.2
            remote_as: 64851
          - address: 10.10.46.2
            remote_as: 64851
          - address: 10.10.47.2
            remote_as: 64851
          - address: 10.10.48.2
            remote_as: 64851
          - address: 10.40.14.2
            remote_as: 64701
ops_ports:
  - name: 1
    ipv4_address: 10.10.41.1/24
  - name: 2
    ipv4_address: 10.10.42.1/24
  - name: 3
    ipv4_address: 10.10.43.1/24
  - name: 4
    ipv4_address: 10.10.44.1/24
  - name: 5
    ipv4_address: 10.10.45.1/24
  - name: 6
    ipv4_address: 10.10.46.1/24
  - name: 7
    ipv4_address: 10.10.47.1/24
  - name: 8
    ipv4_address: 10.10.48.1/24
  - name: 9
    ipv4_address: 10.40.14.1/24
