---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5]
    bgp_routers:
      - as_number: 64901
        router_id: 10.20.21.2
        networks: [10.20.21.0/24, 10.20.22.0/24, 10.20.23.0/24,  10.20.24.0/24, 10.50.12.0/24]
        neighbors:
          - address: 10.20.21.1
            remote_as: 64850
          - address: 10.20.22.1
            remote_as: 64850
          - address: 10.20.23.1
            remote_as: 64850
          - address: 10.20.24.1
            remote_as: 64850
          - address: 10.50.12.1
            remote_as: 64903

ops_ports:
  - name: 1
    ipv4_address: 10.20.21.2/24
  - name: 2
    ipv4_address: 10.20.22.2/24
  - name: 3
    ipv4_address: 10.20.23.2/24
  - name: 4
    ipv4_address: 10.20.24.2/24
  - name: 5
    ipv4_address: 10.50.12.1/24
  - name: 6
  - name: 7
  - name: 8
