---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5]
    bgp_routers:
      - as_number: 64900
        router_id: 10.20.11.2
        networks: [10.20.11.0/24, 10.20.12.0/24, 10.20.13.0/24,  10.20.14.0/24, 10.50.11.0/24]
        neighbors:
          - address: 10.20.11.1
            remote_as: 64850
          - address: 10.20.12.1
            remote_as: 64850
          - address: 10.20.13.1
            remote_as: 64850
          - address: 10.20.14.1
            remote_as: 64850
          - address: 10.50.11.1
            remote_as: 64903

ops_ports:
  - name: 1
    ipv4_address: 10.20.11.2/24
  - name: 2
    ipv4_address: 10.20.12.2/24
  - name: 3
    ipv4_address: 10.20.13.2/24
  - name: 4
    ipv4_address: 10.20.14.2/24
  - name: 5
    ipv4_address: 10.50.11.1/24
  - name: 6
  - name: 7
  - name: 8
