---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3]
    bgp_routers:
      - as_number: 65005
        router_id: 172.16.21.2
        networks: [172.16.21.0/24, 172.16.50.0/24, 172.16.51.0/24]
        neighbors:
          - address: 172.16.21.1
            remote_as: 65002

ops_ports:
  - name: 1
    ipv4_address: 172.16.21.2/24
  - name: 2
    ipv4_address: 172.16.50.1/24
  - name: 3
    ipv4_address: 172.16.51.1/24
  - name: 4
  - name: 5
  - name: 6
  - name: 7
  - name: 8
