---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5]
    bgp_routers:
      - as_number: 64900
        router_id: 10.20.15.2
        networks: [10.20.15.0/24, 10.20.16.0/24, 10.20.17.0/24,  10.20.18.0/24, 10.50.13.0/24]
        neighbors:
          - address: 10.20.15.1
            remote_as: 64851
          - address: 10.20.16.1
            remote_as: 64851
          - address: 10.20.17.1
            remote_as: 64851
          - address: 10.20.18.1
            remote_as: 64851
          - address: 10.50.13.1
            remote_as: 64904

ops_ports:
  - name: 1
    ipv4_address: 10.20.15.2/24
  - name: 2
    ipv4_address: 10.20.16.2/24
  - name: 3
    ipv4_address: 10.20.17.2/24
  - name: 4
    ipv4_address: 10.20.18.2/24
  - name: 5
    ipv4_address: 10.50.13.1/24
  - name: 6
  - name: 7
  - name: 8
