---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64850
        router_id: 10.10.14.2
        networks: [10.10.14.0/24, 10.10.24.0/24, 10.10.34.0/24, 10.10.44.0/24, 10.20.14.0/24, 10.20.24.0/24]
        neighbors:
          - address: 10.10.14.1
            remote_as: 64700
          - address: 10.10.24.1
            remote_as: 64700
          - address: 10.10.34.1
            remote_as: 64700
          - address: 10.10.44.1
            remote_as: 64700
          - address: 10.20.14.2
            remote_as: 64900
          - address: 10.20.24.2
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.10.14.2/24
  - name: 2
    ipv4_address: 10.10.24.2/24
  - name: 3
    ipv4_address: 10.10.34.2/24
  - name: 4
    ipv4_address: 10.10.44.2/24
  - name: 5
    ipv4_address: 10.20.14.1/24
  - name: 6
    ipv4_address: 10.20.24.1/24
  - name: 7
  - name: 8
