---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64850
        router_id: 10.10.13.2
        networks: [10.10.13.0/24, 10.10.23.0/24, 10.10.33.0/24, 10.10.43.0/24, 10.20.13.0/24, 10.20.23.0/24]
        neighbors:
          - address: 10.10.13.1
            remote_as: 64700
          - address: 10.10.23.1
            remote_as: 64700
          - address: 10.10.33.1
            remote_as: 64700
          - address: 10.10.43.1
            remote_as: 64700
          - address: 10.20.13.2
            remote_as: 64900
          - address: 10.20.23.2
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.10.13.2/24
  - name: 2
    ipv4_address: 10.10.23.2/24
  - name: 3
    ipv4_address: 10.10.33.2/24
  - name: 4
    ipv4_address: 10.10.43.2/24
  - name: 5
    ipv4_address: 10.20.13.1/24
  - name: 6
    ipv4_address: 10.20.23.1/24
  - name: 7
  - name: 8
