---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3]
    bgp_routers:
      - as_number: 65001
        router_id: 172.16.1.2
        networks: [172.16.1.0/24, 172.16.11.0/24, 172.16.12.0/24]
        neighbors:
          - address: 172.16.1.1
            remote_as: 65000
          - address: 172.16.11.2
            remote_as: 65003
          - address: 172.16.12.2
            remote_as: 65004

ops_ports:
  - name: 1
    ipv4_address: 172.16.1.2/24
  - name: 2
    ipv4_address: 172.16.11.1/24
  - name: 3
    ipv4_address: 172.16.12.1/24
  - name: 4
  - name: 5
  - name: 6
  - name: 7
  - name: 8
