---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64851
        router_id: 10.10.16.2
        networks: [10.10.16.0/24, 10.10.26.0/24, 10.10.36.0/24, 10.10.46.0/24, 10.20.16.0/24, 10.20.26.0/24]
        neighbors:
          - address: 10.10.16.1
            remote_as: 64700
          - address: 10.10.26.1
            remote_as: 64700
          - address: 10.10.36.1
            remote_as: 64700
          - address: 10.10.46.1
            remote_as: 64700
          - address: 10.20.16.2
            remote_as: 64900
          - address: 10.20.26.2
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.10.16.2/24
  - name: 2
    ipv4_address: 10.10.26.2/24
  - name: 3
    ipv4_address: 10.10.36.2/24
  - name: 4
    ipv4_address: 10.10.46.2/24
  - name: 5
    ipv4_address: 10.20.16.1/24
  - name: 6
    ipv4_address: 10.20.26.1/24
  - name: 7
  - name: 8
