---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64851
        router_id: 10.10.18.2
        networks: [10.10.18.0/24, 10.10.28.0/24, 10.10.38.0/24, 10.10.48.0/24, 10.20.18.0/24, 10.20.28.0/24]
        neighbors:
          - address: 10.10.18.1
            remote_as: 64700
          - address: 10.10.28.1
            remote_as: 64700
          - address: 10.10.38.1
            remote_as: 64700
          - address: 10.10.48.1
            remote_as: 64700
          - address: 10.20.18.2
            remote_as: 64900
          - address: 10.20.28.2
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.10.18.2/24
  - name: 2
    ipv4_address: 10.10.28.2/24
  - name: 3
    ipv4_address: 10.10.38.2/24
  - name: 4
    ipv4_address: 10.10.48.2/24
  - name: 5
    ipv4_address: 10.20.18.1/24
  - name: 6
    ipv4_address: 10.20.28.1/24
  - name: 7
  - name: 8
