---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64851
        router_id: 10.10.17.2
        networks: [10.10.17.0/24, 10.10.27.0/24, 10.10.37.0/24, 10.10.47.0/24, 10.20.17.0/24, 10.20.27.0/24]
        neighbors:
          - address: 10.10.17.1
            remote_as: 64700
          - address: 10.10.27.1
            remote_as: 64700
          - address: 10.10.37.1
            remote_as: 64700
          - address: 10.10.47.1
            remote_as: 64700
          - address: 10.20.17.2
            remote_as: 64900
          - address: 10.20.27.2
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.10.17.2/24
  - name: 2
    ipv4_address: 10.10.27.2/24
  - name: 3
    ipv4_address: 10.10.37.2/24
  - name: 4
    ipv4_address: 10.10.47.2/24
  - name: 5
    ipv4_address: 10.20.17.1/24
  - name: 6
    ipv4_address: 10.20.27.1/24
  - name: 7
  - name: 8
