---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64850
        router_id: 10.10.11.2
        networks: [10.10.11.0/24, 10.10.21.0/24, 10.10.31.0/24, 10.10.41.0/24, 10.20.11.0/24, 10.20.21.0/24]
        neighbors:
          - address: 10.10.11.1
            remote_as: 64700
          - address: 10.10.21.1
            remote_as: 64700
          - address: 10.10.31.1
            remote_as: 64700
          - address: 10.10.41.1
            remote_as: 64700
          - address: 10.20.11.2
            remote_as: 64900
          - address: 10.20.21.2
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.10.11.2/24
  - name: 2
    ipv4_address: 10.10.21.2/24
  - name: 3
    ipv4_address: 10.10.31.2/24
  - name: 4
    ipv4_address: 10.10.41.2/24
  - name: 5
    ipv4_address: 10.20.11.1/24
  - name: 6
    ipv4_address: 10.20.21.1/24
  - name: 7
  - name: 8
