---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3]
    bgp_routers:
      - as_number: 65002
        router_id: 172.16.2.2
        networks: [172.16.2.0/24, 172.16.21.0/24, 172.16.22.0/24]
        neighbors:
          - address: 172.16.2.1
            remote_as: 65000
          - address: 172.16.21.2
            remote_as: 65005
          - address: 172.16.22.2
            remote_as: 65006

ops_ports:
  - name: 1
    ipv4_address: 172.16.2.2/24
  - name: 2
    ipv4_address: 172.16.21.1/24
  - name: 3
    ipv4_address: 172.16.22.1/24
  - name: 4
  - name: 5
  - name: 6
  - name: 7
  - name: 8
